version: 2
registries: []

updates:
  - package-ecosystem: "pip"
    directory: "/nuclear_war"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/wopr_visualizer"
    schedule:
      interval: "weekly"
