version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/nuclear_war"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/wopr_visualizer"
    schedule:
      interval: "weekly"
